# Generated by Django 4.2.7 on 2024-03-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set(),
        ),
    ]
